language: node_js
node_js:
  - "stable"

dist: focal  # Ubuntu 20.04

install:
  - npm install  # Install dependencies

script:
  - npm run build  # Build the project (Make sure your package.json has a "build" script)

deploy:
  provider: pages
  keep_history: true  # Instead of `skip_cleanup`
  github_token: $GITHUB_TOKEN  # Correct environment variable
  local_dir: build  # The folder that contains your built files
  on:
    branch: main  # Deploy only on main branch

